{
  "hash": "7bb2484b40c24360118decde57e510b7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment3: Verify the Claim: Poverty Change in Philadelphia\"\nauthor: \"Chenyan Zhao\"\ndate: September 17, 2026\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-summary: \"Show code\"\n    embed-resources: true\n---\n\n## Part 1 Reconstruct\n\n### Article and analytical scope\n\nI analyze Alfred Lubrano's 2018 WHYY / Philadelphia Inquirer article, “New\nCensus figures on Philly neighborhoods show inequality, high numbers of whites\nliving in poverty.” **The article reports that Eastwick's poverty rate increased\nfrom 12 percent in the 2006–2010 ACS period to 26 percent in the 2013–2017 ACS\nperiod. It also states that the newer figures come from the American Community\nSurvey (ACS) five-year estimates.**\n\nThe article reports results for Philadelphia neighborhoods, but neighborhoods\nsuch as Eastwick are not official Census geographies. The Census Bureau\npublishes ACS data for Census tracts, which have GEOIDs and defined boundaries.\nSince the article does not provide its tract-to-neighborhood crosswalk or\nboundary file, I cannot exactly reproduce its neighborhood-level estimates.\nTherefore, I reconstruct and test the article's general poverty-change claim\nat the Census-tract level for Philadelphia County, Pennsylvania.\n\nSource article:\n<https://whyy.org/articles/new-census-figures-on-philly-neighborhoods-show-inequality-high-numbers-of-whites-living-in-poverty/>\n\n### Variables\n\nI use ACS detailed table `B17001`, *Poverty Status in the Past 12 Months by\nSex by Age*. The table provides a poverty count and its margin of error, as\nwell as the population for whom poverty status is determined.\n\n- `B17001_001`: Total population for whom poverty status is determined. I use\n  this as the denominator.\n- `B17001_002`: Population with income in the past 12 months below the poverty\n  level. I use this as the numerator.\n\nFor each Census tract, the poverty rate will be calculated as:\n\n$$\n\\text{Poverty rate} =\n\\frac{\\text{B17001\\_002}}{\\text{B17001\\_001}}\n$$\n\nThese variables match the article's general discussion of overall poverty\nrates. They do not measure poverty only for a specific age group, sex, or race.\nThe article also discusses white poverty in Holmesburg, but that would require\na separate race-specific analysis and a clear definition of “white” that the\narticle does not provide. I therefore focus this analysis on overall poverty.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get data\nget_poverty <- function(yr) {\n  get_acs(\n    geography = \"tract\",\n    variables = c(\n      below_poverty = \"B17001_002\",\n      total = \"B17001_001\"\n    ),\n    state = \"PA\",\n    county = \"Philadelphia\",\n    year = yr,\n    survey = \"acs5\",\n    output = \"wide\"\n  ) %>%\n    mutate(period = paste0(yr - 4, \"-\", yr)\n  )\n}\n\n# Retrieve and combine tract-level poverty data.\npoverty_change <- bind_rows(\n  get_poverty(2010),\n  get_poverty(2017)\n)\n```\n:::\n\n\n\n::: {.cell tbl-cap='Table 1. Census tracts retrieved from ACS 5-year data'}\n\n```{.r .cell-code}\npoverty_change %>%\n  count(period, name = \"Number of Census tracts\") %>%\n  knitr::kable(\n    col.names = c(\"ACS period\", \"Number of Census tracts\")\n  )\n```\n\n::: {.cell-output-display}\n\n\n|ACS period | Number of Census tracts|\n|:----------|-----------------------:|\n|2006-2010  |                     384|\n|2013-2017  |                     384|\n\n\n:::\n:::\n\n\n### Years, survey, and assumptions\n\nI use the 2010 and 2017 ACS five-year releases because they match the two periods discussed in the article: 2006–2010 and 2013–2017. I use `acs5` because tract-level data are available in the five-year ACS, while the one-year ACS does not provide tract estimates.\n\nThe article does not explain exactly which Census table, poverty-rate denominator, or neighborhood boundaries it used. I therefore use table `B17001` and calculate poverty rates for Census tracts in Philadelphia County. This cannot exactly reproduce the article’s neighborhood results because neighborhoods do not have official Census boundaries. I also match tracts by `GEOID` before comparing the two periods.\n\nThe two ACS periods do not overlap, so they do not use the same survey years. However, each estimate still represents a five-year average. For this reason, the results show changes in estimated tract poverty rates, not changes experienced by the same individual residents.\n\n## Part 2 — Test\n\n### Check missing values\n\nFirst, I calculate poverty rates and their margins of error for all returned\ntract-period observations. \n\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty_rates <- poverty_change %>%\n  mutate(\n    poverty_rate = below_povertyE / totalE,\n    poverty_rate_moe = moe_prop(\n      below_povertyE,\n      totalE,\n      below_povertyM,\n      totalM\n    )\n  )\n```\n:::\n\n\nI then check which Census tracts have missing poverty-rate results in either\nACS period.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmissing_tracts <- poverty_rates %>%\n  filter(\n    is.na(poverty_rate) |\n    is.na(poverty_rate_moe)\n  ) %>%\n  select(\n    GEOID,\n    NAME,\n    period,\n    totalE,\n    totalM,\n    below_povertyE,\n    below_povertyM,\n    poverty_rate,\n    poverty_rate_moe\n  )\n\nmissing_tracts\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 15 × 9\n   GEOID   NAME  period totalE totalM below_povertyE below_povertyM poverty_rate\n   <chr>   <chr> <chr>   <dbl>  <dbl>          <dbl>          <dbl>        <dbl>\n 1 421010… Cens… 2006-…      0    109              0            109          NaN\n 2 421019… Cens… 2006-…      0    109              0            109          NaN\n 3 421019… Cens… 2006-…      0    109              0            109          NaN\n 4 421019… Cens… 2006-…      0    109              0            109          NaN\n 5 421019… Cens… 2006-…      0    109              0            109          NaN\n 6 421019… Cens… 2006-…      0    109              0            109          NaN\n 7 421019… Cens… 2006-…      0    109              0            109          NaN\n 8 421010… Cens… 2013-…      0     10              0             10          NaN\n 9 421019… Cens… 2013-…      0     10              0             10          NaN\n10 421019… Cens… 2013-…      0     10              0             10          NaN\n11 421019… Cens… 2013-…      0     10              0             10          NaN\n12 421019… Cens… 2013-…      0     10              0             10          NaN\n13 421019… Cens… 2013-…      0     10              0             10          NaN\n14 421019… Cens… 2013-…      0     10              0             10          NaN\n15 421019… Cens… 2013-…      0     10              0             10          NaN\n# ℹ 1 more variable: poverty_rate_moe <dbl>\n```\n\n\n:::\n:::\n\n\nThe missing results come from 15 tract-period observations: seven in\n2006–2010 and eight in 2013–2017. In every case, the estimated population for\nwhom poverty status was determined (`totalE`) is zero, so a poverty rate cannot\nbe calculated. Seven tracts have this problem in both periods, while Census\nTract 9806 has a usable estimate in 2006–2010 but not in 2013–2017. I do not\ntreat these missing rates as zero. I exclude them because zero means there is\nno estimated population in the poverty universe, not that the poverty rate is\nzero.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty_rates_clean <- poverty_rates %>%\n  filter(\n    !is.na(poverty_rate),\n    !is.na(poverty_rate_moe)\n  )\n```\n:::\n\n\n### Reliability\n\nI calculate the coefficient of variation using the poverty-rate margin of\nerror. Following Jurjevich et al. (2018), estimates with a CV below 12 percent\nare classified as reliable; estimates from 12 to 40 percent are somewhat\nreliable; and estimates above 40 percent are unreliable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty_rates_clean <- poverty_rates_clean %>%\n  mutate(\n    cv = (poverty_rate_moe / 1.645) / poverty_rate * 100,\n    reliability = case_when(\n      cv < 12 ~ \"Reliable\",\n      cv <= 40 ~ \"Somewhat reliable\",\n      TRUE ~ \"Unreliable\"\n    )\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty_rates_clean %>%\n  count(period, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  period    reliability           n\n  <chr>     <chr>             <int>\n1 2006-2010 Reliable             11\n2 2006-2010 Somewhat reliable   321\n3 2006-2010 Unreliable           45\n4 2013-2017 Reliable             22\n5 2013-2017 Somewhat reliable   332\n6 2013-2017 Unreliable           22\n```\n\n\n:::\n:::\n\n\nThe table reports the reliability of every usable tract estimate in the\n2013–2017 ACS period. The color-coded flags encourage cautious interpretation\nrather than automatically excluding valid ACS observations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty_rates_clean %>%\n  filter(period == \"2013-2017\") %>%\n  mutate(\n    reliability_symbol = case_when(\n      cv < 12  ~ \"🟢\",\n      cv <= 40 ~ \"🟡\",\n      TRUE     ~ \"🔴\"\n    ),\n    tract = str_remove(NAME, \", Philadelphia County, Pennsylvania\"),\n    rate = poverty_rate,\n    rate_moe = poverty_rate_moe\n  ) %>%\n  arrange(desc(cv)) %>%\n  select(reliability_symbol, tract, rate, rate_moe, cv, reliability) %>%\n  gt() %>%\n  tab_header(\n    title = \"Reliability of Philadelphia tract poverty-rate estimates\",\n    subtitle = \"2013-2017 ACS five-year estimates\"\n  ) %>%\n  cols_label(\n    reliability_symbol = \"\",\n    tract = \"Census tract\",\n    rate = \"Poverty rate\",\n    rate_moe = \"MOE\",\n    cv = \"CV (%)\",\n    reliability = \"Reliability\"\n  ) %>%\n  fmt_percent(columns = rate, decimals = 1) %>%\n  fmt_percent(columns = rate_moe, decimals = 1) %>%\n  fmt_number(columns = cv, decimals = 1) %>%\n  cols_align(align = \"center\", columns = reliability_symbol) %>%\n  tab_source_note(\n    \"Source: U.S. Census Bureau ACS five-year estimates via tidycensus. Jurjevich et al. (2018) thresholds: CV < 12% reliable; 12-40% somewhat reliable; > 40% unreliable.\"\n  )%>%\n  tab_options(\n    # keep the sheet into a box, so that it will be easier to read.\n    container.height = px(500),\n    container.overflow.y = TRUE,\n    container.width = pct(100),\n    container.overflow.x = TRUE\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ytpueuddnb\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:100%;height:500px;\">\n<style>#ytpueuddnb table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ytpueuddnb thead, #ytpueuddnb tbody, #ytpueuddnb tfoot, #ytpueuddnb tr, #ytpueuddnb td, #ytpueuddnb th {\n  border-style: none;\n}\n\n#ytpueuddnb p {\n  margin: 0;\n  padding: 0;\n}\n\n#ytpueuddnb .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ytpueuddnb .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ytpueuddnb .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ytpueuddnb .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ytpueuddnb .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ytpueuddnb .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ytpueuddnb .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ytpueuddnb .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ytpueuddnb .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ytpueuddnb .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ytpueuddnb .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ytpueuddnb .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ytpueuddnb .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ytpueuddnb .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ytpueuddnb .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ytpueuddnb .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ytpueuddnb .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ytpueuddnb .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ytpueuddnb .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ytpueuddnb .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ytpueuddnb .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ytpueuddnb .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ytpueuddnb .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ytpueuddnb .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ytpueuddnb .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ytpueuddnb .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ytpueuddnb .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ytpueuddnb .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ytpueuddnb .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ytpueuddnb .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ytpueuddnb .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ytpueuddnb .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ytpueuddnb .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ytpueuddnb .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ytpueuddnb .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ytpueuddnb .gt_left {\n  text-align: left;\n}\n\n#ytpueuddnb .gt_center {\n  text-align: center;\n}\n\n#ytpueuddnb .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ytpueuddnb .gt_font_normal {\n  font-weight: normal;\n}\n\n#ytpueuddnb .gt_font_bold {\n  font-weight: bold;\n}\n\n#ytpueuddnb .gt_font_italic {\n  font-style: italic;\n}\n\n#ytpueuddnb .gt_super {\n  font-size: 65%;\n}\n\n#ytpueuddnb .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ytpueuddnb .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ytpueuddnb .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ytpueuddnb .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ytpueuddnb .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ytpueuddnb .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ytpueuddnb .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ytpueuddnb .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ytpueuddnb div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"6\" class=\"gt_heading gt_title gt_font_normal\" style>Reliability of Philadelphia tract poverty-rate estimates</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"6\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>2013-2017 ACS five-year estimates</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"reliability_symbol\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"tract\">Census tract</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"rate\">Poverty rate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"rate_moe\">MOE</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"cv\">CV (%)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"reliability\">Reliability</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 9891</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">92.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">220.4%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">144.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 9800</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">4.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">85.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 231</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">0.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">0.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">66.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 256</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">3.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">3.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">64.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 9801</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">13.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">13.4%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">61.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 386</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">3.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">3.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">59.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 9802</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">11.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">51.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 340</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">9.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">47.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 347.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">2.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">1.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">47.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 10.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">6.4%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">4.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">46.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 220</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">1.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">1.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">45.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 363.03</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">5.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">4.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">44.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 29</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">17.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">12.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">43.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 341</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">9.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">42.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 365.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">12.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">42.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 8.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">13.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">41.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 4.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">4.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">2.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">41.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 236</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">10.4%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">41.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 366</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">4.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">3.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">40.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 356.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">2.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">1.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">40.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 235</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">9.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">40.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 365.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">6.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">4.4%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">40.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 352</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">5.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">3.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">40.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 10.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">5.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">3.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">39.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 40.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">7.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">4.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">39.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 12.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">3.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">2.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">39.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 385</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">7.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">4.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">39.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 344</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">5.4%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">3.4%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">38.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 362.03</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">5.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">3.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">38.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 361</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">14.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">38.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 17</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">2.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">1.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">38.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 373</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">2.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">1.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">38.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 18</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">6.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">4.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">37.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 306</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">11.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">36.8</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 42.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">16.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">36.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 136.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">2.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">1.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">36.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 142</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">8.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">5.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">36.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 219</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">5.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">3.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">36.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 353.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">7.4%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">4.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">35.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 215</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">15.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">34.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 42.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">15.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">34.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 263.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">11.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">34.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 212</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">7.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">4.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">34.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 320</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">14.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">34.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 348.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">13.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">34.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 262</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">7.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">4.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">34.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 27.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">11.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">33.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 317</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">13.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">33.8</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 180.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">13.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">33.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 347.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">9.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">5.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">33.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 209</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">12.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">33.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 372</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">13.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">33.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 387</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">8.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">4.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">33.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 367</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">6.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">3.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">32.8</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 217</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">3.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">1.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">32.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 101</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">24.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">13.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">32.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 22</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">24.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">13.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">32.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 38</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">8.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">4.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">32.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 292</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">18.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">32.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 8.03</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">10.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">5.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">32.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 325</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">29.4%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">15.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">32.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 315.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">16.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">31.8</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 321</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">29.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">15.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">31.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 339</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">15.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">31.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 8.04</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">8.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">4.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">31.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 342</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">13.4%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">31.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 260</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">12.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">31.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 310</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">20.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">31.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 379</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">12.4%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">31.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 141</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">34.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">17.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">31.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 255</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">7.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">3.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">30.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 323</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">12.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">30.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 358</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">7.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">3.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">30.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 362.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">4.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">2.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">30.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 82</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">22.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">11.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">30.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 134.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">7.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">3.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">30.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 266</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">14.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.4%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">30.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 183</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">5.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">2.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">30.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 363.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">5.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">2.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">30.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 259</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">10.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">5.4%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">30.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 211</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">12.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">30.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 348.03</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">5.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">2.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">30.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 98.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">20.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">29.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 117</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">35.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">17.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">29.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 143</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">11.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">5.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">29.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 363.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">10.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">5.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">29.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 54</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">13.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">29.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 55</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">17.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">29.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 134.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">7.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">3.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">29.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 73</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">29.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">14.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">29.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 338</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">13.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">29.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 261</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">21.4%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">29.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 238</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">12.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">29.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 302</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">19.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">29.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 388</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">6.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">3.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">29.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 348.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">9.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">4.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">29.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 23</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">7.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">3.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">28.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 125</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">13.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.4%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">28.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 252</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">30.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">14.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">28.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 346</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">16.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">28.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 264</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">10.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">4.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">28.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 331.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">16.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">28.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 326</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">22.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">28.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 172.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">40.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">18.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">27.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 351</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">10.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">4.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">27.8</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 161</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">26.4%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">12.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">27.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 216</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">16.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">27.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 98.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">19.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">27.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 332</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">4.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">2.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">27.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 201.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">28.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">12.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">27.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 28.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">18.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">27.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 258</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">5.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">2.4%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">27.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 16</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">7.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">3.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">27.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 362.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">9.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">4.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">26.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 336</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">18.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">26.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 349</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">16.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">26.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 39.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">11.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">5.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">26.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 329</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">22.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">26.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 384</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">4.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">2.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">26.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 263.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">13.4%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">5.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">26.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 333</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">14.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">26.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 86.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">18.4%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">26.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 136.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">9.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">4.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">26.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 274.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">21.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">26.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 79</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">12.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">5.4%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">26.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 307</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">26.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">11.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">26.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 15</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">13.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">5.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">26.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 378</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">17.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">25.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 218</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">18.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">25.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 213</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">9.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">4.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">25.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 114</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">17.4%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">25.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 1</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">7.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">2.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">25.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 21</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">23.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">25.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 179</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">26.4%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">11.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">25.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 115</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">15.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">25.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 364</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">42.4%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">17.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">25.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 135</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">15.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.4%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">25.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 25</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">14.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">24.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 11.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">18.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">24.8</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 19</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">11.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">4.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">24.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 318</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">24.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">24.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 60</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">34.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">14.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">24.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 112</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">37.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">15.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">24.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 316</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">26.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">24.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 337.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">9.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">3.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">24.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 308</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">15.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">24.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 157</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">26.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">24.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 131</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">30.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">12.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">23.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 275</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">25.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">23.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 207</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">16.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">23.8</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 257</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">9.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">3.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">23.8</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 28.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">6.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">2.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">23.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 40.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">20.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">23.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 309</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">26.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">23.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 204</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">34.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">13.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">23.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 312</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">31.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">12.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">23.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 158</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">14.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">5.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">23.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 120</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">13.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">5.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">23.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 353.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">10.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">3.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">23.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 330</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">31.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">12.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">23.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 61</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">25.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">23.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 237</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">9.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">3.4%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">23.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 356.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">8.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">3.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">23.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 84</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">27.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">23.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 267</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">24.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.4%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">23.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 37.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">21.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">22.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 331.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">14.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">5.4%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">22.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 268</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">22.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">22.8</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 271</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">15.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">5.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">22.8</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 277</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">29.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">11.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">22.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 93</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">28.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">22.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 360</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">10.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">4.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">22.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 70</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">24.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">22.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 334</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">20.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">22.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 253</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">19.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">22.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 81.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">43.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">16.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">22.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 381</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">25.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">22.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 13</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">7.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">2.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">22.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 20</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">16.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">22.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 81.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">34.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">12.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">22.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 133</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">32.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">11.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">22.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 281</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">30.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">11.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">22.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 249</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">39.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">14.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">22.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 113</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">28.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.4%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">21.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 359</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">8.4%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">3.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">21.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 382</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">32.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">11.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">21.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 210</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">23.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">21.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 375</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">23.4%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.4%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">21.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 203</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">46.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">16.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">21.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 2</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">37.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">13.4%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">21.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 276</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">17.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">21.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 121</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">30.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">21.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 27.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">28.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">21.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 30.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">25.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">21.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 279.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">29.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">21.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 65</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">29.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">21.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 119</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">30.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">21.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 139</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">41.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">14.4%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">20.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 171</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">24.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">20.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 56</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">48.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">16.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">20.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 243</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">32.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">11.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">20.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 190</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">31.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">20.8</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 345.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">16.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">5.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">20.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 289.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">31.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">20.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 3</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">8.4%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">2.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">20.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 71.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">37.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">12.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">20.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 64</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">30.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">20.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 357.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">21.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">20.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 244</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">34.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">11.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">20.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 86.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">19.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">20.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 180.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">24.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">20.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 14</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">13.4%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">4.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">20.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 62</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">38.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">12.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">20.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 389</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">35.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">11.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">20.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 39.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">21.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">20.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 118</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">24.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">20.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 80</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">26.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">20.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 335</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">26.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">20.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 355</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">15.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">5.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">19.8</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 265</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">23.4%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">19.8</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 301</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">35.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">11.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">19.8</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 7</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">18.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">19.8</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 72</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">34.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">11.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">19.8</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 71.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">34.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">11.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">19.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 24</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">11.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">3.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">19.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 191</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">32.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">19.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 380</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">28.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">19.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 4.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">18.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">5.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">19.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 102</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">40.4%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">12.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">19.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 282</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">30.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">19.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 284</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">38.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">12.4%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">19.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 149</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">38.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">12.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">19.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 278</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">30.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">19.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 78</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">24.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">19.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 11.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">18.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">5.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">19.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 241</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">43.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">13.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">19.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 103</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">40.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">12.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">19.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 173</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">31.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">19.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 32</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">36.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">11.4%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">19.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 200</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">58.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">18.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">19.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 274.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">27.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">19.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 248</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">23.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">18.8</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 239</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">28.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">18.8</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 83.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">33.4%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">18.8</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 273</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">17.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">5.4%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">18.8</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 272</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">15.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">4.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">18.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 83.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">22.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">18.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 12.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">10.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">3.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">18.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 311.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">12.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">3.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">18.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 33</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">35.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">18.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 174</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">43.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">13.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">18.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 104</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">45.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">13.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">18.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 337.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">19.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">18.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 315.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">24.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">18.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 290</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">43.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">13.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">18.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 88.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">64.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">19.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">18.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 283</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">33.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">18.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 6</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">13.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">4.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">18.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 145</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">44.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">13.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">17.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 169.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">45.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">13.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">17.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 269</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">15.4%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">4.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">17.8</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 30.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">18.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">5.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">17.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 146</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">28.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.4%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">17.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 254</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">11.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">3.4%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">17.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 110</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">48.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">13.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">17.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 122.03</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">25.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">17.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 169.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">37.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">17.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 377</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">45.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">12.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">17.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 242</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">34.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">17.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 206</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">24.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">17.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 314.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">25.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">17.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 137</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">31.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">17.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 270</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">14.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">4.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">17.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 168</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">46.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">13.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">17.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 148</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">53.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">15.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">17.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 37.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">31.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">16.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 311.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">27.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">16.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 184</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">13.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">3.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">16.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 305.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">35.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">16.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 41.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">33.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">16.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 205</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">32.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">16.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 74</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">33.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">16.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 111</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">39.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">16.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 140</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">41.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">11.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">16.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 285</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">38.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">16.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 87.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">25.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">16.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 96</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">35.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">16.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 85</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">36.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">16.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 41.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">40.4%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">16.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 100</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">29.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">16.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 279.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">37.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">16.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 106</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">44.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">11.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">16.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 9.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">20.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">5.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">16.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 160</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">10.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">2.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">16.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 122.04</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">19.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">5.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">16.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 313</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">31.4%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">16.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 95</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">38.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">16.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 31</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">21.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">5.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">15.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 9.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">24.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">15.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 280</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">37.4%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">15.8</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 188</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">48.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">12.4%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">15.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 36</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">45.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">11.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">15.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 132</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">33.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">15.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 69</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">62.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">16.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">15.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 300</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">35.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">15.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 319</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">19.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">5.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">15.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 214</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">20.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">5.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">15.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 376</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">37.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">15.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 147</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">62.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">15.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">15.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 240</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">26.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">15.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 197</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">44.4%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">11.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">15.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 305.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">31.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">15.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 170</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">34.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">15.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 195.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">53.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">13.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">15.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 357.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">25.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">15.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 152</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">57.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">14.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">15.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 345.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">22.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">5.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">14.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 105</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">44.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">11.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">14.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 151.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">50.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">12.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">14.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 165</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">58.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">13.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">14.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 286</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">34.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">14.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 390</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">36.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">14.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 293</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">57.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">13.4%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">14.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 246</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">41.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">14.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 298</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">33.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">14.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 199</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">62.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">14.4%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">14.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 208</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">27.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">14.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 288</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">43.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">14.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 108</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">43.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">14.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 138</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">33.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">14.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 67</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">32.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">13.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 107</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">41.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">13.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 202</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">46.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">13.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 144</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">32.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">13.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 87.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">33.4%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.4%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">13.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 63</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">44.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">13.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 192</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">52.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">11.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">13.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 166</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">51.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">11.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">13.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 77</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">45.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">13.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 291</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">46.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">13.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 92</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">43.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.4%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">13.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 66</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">41.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">13.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 247</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">33.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">13.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 294</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">55.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">11.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">13.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 177.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">55.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">11.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">13.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 151.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">49.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">13.0</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 167.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">48.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">12.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 156</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">43.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">12.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 383</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">57.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">12.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">12.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 198</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">50.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">12.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 172.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">44.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">12.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 314.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">28.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">5.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">12.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 88.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">64.2%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">12.9%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">12.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟡</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 195.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">50.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">12.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Somewhat reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 91</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">50.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">11.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 122.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">32.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">11.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 162</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">47.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">11.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 369</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">45.1%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">11.8</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 178</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">56.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">11.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 287</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">41.7%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.0%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">11.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 176.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">61.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">11.6%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">11.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 299</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">49.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">11.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 176.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">63.4%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">11.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">11.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 5</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">34.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.4%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">11.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 94</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">43.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">10.8</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 163</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">54.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">10.8</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 201.01</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">46.8%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">10.8</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 164</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">49.9%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.7%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">10.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 289.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">39.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">10.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 245</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">59.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">10.1%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">10.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 167.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">36.3%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">5.8%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">9.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 175</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">59.6%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">9.2%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">9.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 109</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">55.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">8.3%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">9.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 177.02</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">59.5%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">7.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 90</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">61.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">7.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">7.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Reliable</td></tr>\n    <tr><td headers=\"reliability_symbol\" class=\"gt_row gt_center\">🟢</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 153</td>\n<td headers=\"rate\" class=\"gt_row gt_right\">68.0%</td>\n<td headers=\"rate_moe\" class=\"gt_row gt_right\">6.5%</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">5.8</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Reliable</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"6\">Source: U.S. Census Bureau ACS five-year estimates via tidycensus. Jurjevich et al. (2018) thresholds: CV &lt; 12% reliable; 12-40% somewhat reliable; &gt; 40% unreliable.</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n### Change over time\n\nNext, I reshape the data so that each tract has one row containing poverty\nrates and margins of error for both ACS periods.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty_wide <- poverty_rates_clean %>%\n  select(\n    GEOID,\n    NAME,\n    period,\n    poverty_rate,\n    poverty_rate_moe\n  ) %>%\n  pivot_wider(\n    names_from = period,\n    values_from = c(poverty_rate, poverty_rate_moe)\n  )\n```\n:::\n\n\nI identify tracts that have usable data in only one period. Those tracts cannot be included in the change test because a difference requires valid estimates and margins of error for both periods.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nincomplete_tracts <- poverty_wide %>%\n  filter(\n    is.na(`poverty_rate_2006-2010`) |\n    is.na(`poverty_rate_2013-2017`) |\n    is.na(`poverty_rate_moe_2006-2010`) |\n    is.na(`poverty_rate_moe_2013-2017`)\n  )\n\nincomplete_tracts\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 6\n  GEOID       NAME                 poverty_rate_2006-20…¹ poverty_rate_2013-20…²\n  <chr>       <chr>                                 <dbl>                  <dbl>\n1 42101980600 Census Tract 9806, …                 0.0978                     NA\n# ℹ abbreviated names: ¹​`poverty_rate_2006-2010`, ²​`poverty_rate_2013-2017`\n# ℹ 2 more variables: `poverty_rate_moe_2006-2010` <dbl>,\n#   `poverty_rate_moe_2013-2017` <dbl>\n```\n\n\n:::\n:::\n\n\nThe ACS reports 90 percent margins of error. I divide each MOE by 1.645 to calculate its standard error, combine the two standard errors to calculate the standard error of the difference, and multiply by 1.645 to obtain the 90 percent margin of error for the change.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty_tested <- poverty_wide %>%\n  filter(\n    !is.na(`poverty_rate_2006-2010`),\n    !is.na(`poverty_rate_2013-2017`),\n    !is.na(`poverty_rate_moe_2006-2010`),\n    !is.na(`poverty_rate_moe_2013-2017`)\n  ) %>%\n  mutate(\n    change = `poverty_rate_2013-2017` -\n      `poverty_rate_2006-2010`,\n\n    se_1 = `poverty_rate_moe_2006-2010` / 1.645,\n    se_2 = `poverty_rate_moe_2013-2017` / 1.645,\n\n    se_diff = sqrt(se_1^2 + se_2^2),\n    moe_diff = se_diff * 1.645,\n\n    z = change / se_diff,\n    significant = abs(z) > 1.645,\n\n    change_direction = case_when(\n      significant & change > 0 ~ \"Significant increase\",\n      significant & change < 0 ~ \"Significant decrease\",\n      TRUE ~ \"Not distinguishable from zero\"\n    )\n  )\n\nchange_counts <- poverty_tested %>%\n  count(change_direction)\n\nchange_counts\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  change_direction                  n\n  <chr>                         <int>\n1 Not distinguishable from zero   313\n2 Significant decrease             27\n3 Significant increase             36\n```\n\n\n:::\n:::\n\n\nOf the 376 Census tracts with usable estimates in both\nperiods, 63 show a statistically detectable\npoverty-rate change at the 90 percent confidence level. The remaining\n313 tracts do not show a change that is\nstatistically distinguishable from zero.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(change_counts, aes(x = change_direction, y = n, fill = change_direction)) +\n  geom_col(width = 0.65, show.legend = FALSE) +\n  geom_text(aes(label = n), hjust = -0.15) +\n  coord_flip() +\n  scale_fill_manual(\n    values = c(\n      \"Significant increase\" = \"#C85A5A\",\n      \"Significant decrease\" = \"#4F81BD\",\n      \"Not distinguishable from zero\" = \"#8A8A8A\"\n    )\n  ) +\n  scale_y_continuous(expand = expansion(mult = c(0, 0.08))) +\n  labs(\n    title = \"Results of the tract-level poverty-rate change test\",\n    subtitle = \"90% confidence tests for 376 matched Philadelphia census tracts\",\n    x = NULL,\n    y = \"Number of census tracts\",\n    caption = \"Source: U.S. Census Bureau, ACS five-year estimates via tidycensus.\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Most Philadelphia census tracts did not have a statistically detectable change in poverty rate.](assignment3_files/figure-html/change-summary-plot-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchange_plot_data <- poverty_tested %>%\n  filter(significant) %>%\n  arrange(desc(abs(change))) %>%\n  slice_head(n = 20) %>%\n  mutate(\n    tract = str_remove(NAME, \", Philadelphia County, Pennsylvania\"),\n    change_pp = change * 100,\n    moe_diff_pp = moe_diff * 100,\n    direction = case_when(\n      change > 0 ~ \"Increase\",\n      TRUE ~ \"Decrease\"\n    )\n  )\n\nggplot(change_plot_data, aes(x = reorder(tract, change_pp), y = change_pp)) +\n  geom_col(aes(fill = direction), width = 0.7) +\n  geom_errorbar(\n    aes(ymin = change_pp - moe_diff_pp, ymax = change_pp + moe_diff_pp),\n    width = 0.25\n  ) +\n  geom_hline(yintercept = 0, linetype = \"dashed\") +\n  coord_flip() +\n  scale_fill_manual(values = c(\"Increase\" = \"#C85A5A\", \"Decrease\" = \"#4F81BD\")) +\n  labs(\n    title = \"Largest statistically detectable poverty-rate changes\",\n    subtitle = \"Twenty largest absolute changes, 2006-2010 versus 2013-2017\",\n    x = NULL,\n    y = \"Change in poverty rate (percentage points)\",\n    fill = NULL,\n    caption = \"Error bars show 90% margins of error; dashed line marks no change. Source: U.S. Census Bureau, ACS five-year estimates via tidycensus.\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Largest statistically detectable tract-level poverty-rate changes, with 90% margins of error.](assignment3_files/figure-html/change-error-bar-plot-1.png){width=864}\n:::\n:::\n\n\n## Part 3 — Adjudicate\n\n**Supported.** The tract results support the article's broader point that\npoverty worsened in some parts of Philadelphia. Of the 376 tracts that could\nbe compared, 36 had a statistically detectable increase in poverty.\n**Not supported.** The results do not support the idea that poverty increased\nacross the city as a whole: 27 tracts had a detectable decrease, and 313 did\nnot show a clear change. The pattern was mixed rather than citywide.\n\n**Cannot be determined.** I cannot verify the article's exact figures for\nEastwick (12% to 26%), Fairhill (61%), or white poverty in Holmesburg. The\narticle does not publish the neighborhood boundaries or the tracts used in\nthose calculations. The Holmesburg claim would also require a race-specific\npoverty measure, while this analysis measures overall poverty.\n\n## Part 4 — Rewrite\n\nNew American Community Survey data show that poverty changed unevenly across\nPhiladelphia between 2006–10 and 2013–17. Among 376 census tracts with\ncomparable estimates, 36 had a clear increase in poverty and 27 had a clear\ndecrease. In the remaining 313 tracts, the estimated changes were too small\nrelative to survey uncertainty to draw a firm conclusion. The results show\nworsening poverty in some parts of the city and declines in others, while the\ndirection of change remains unclear across most tracts. The article's exact\nfigures for Eastwick, Fairhill, and Holmesburg cannot be confirmed because the\nneighborhood boundaries used in those calculations were not published.\n",
    "supporting": [
      "assignment3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}