{
  "hash": "15fdaa1ca8099e2bcadecd376c686125",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Who Do We Know the Least About?\"\nsubtitle: \"Measuring uncertainty in American Community Survey data\"\nauthor: \"Chenyan Zhao\"\ndate: September 7, 2026\nformat:\n  html:\n    toc: true\n    code-fold: false\nexecute:\n  # Keep the unfinished template display-only until its placeholders are filled.\n  eval: true\n  warning: false\n  message: false\n---\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidycensus)\n```\n:::\n\n\n---\n\n## The question\n\nEvery number the American Community Survey publishes is an estimate drawn from a\nsample, not a count. That means every number comes with a margin of error — a\nstatement about how wrong it might be.\n\nMost people ignore it. In this assignment, you won't.\n\n\nIn this analysis, I look at **median gross rent** across counties in **New York State**. I compare the margins of error for these estimates to identify which counties’ rent data are measured most and least reliably.\n\n---\n\n## Choosing what to measure\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_state    <- \"NY\"             # two-letter abbreviation, in quotes\nmy_variable <- \"B25064_001\"     # the variable code, in quotes\n```\n:::\n\n\n## Pulling the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- get_acs(\n  geography = \"county\",\n  variables = my_variable,\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\"\n)\n```\n:::\n\n\nLet's look at what came back.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 62  5\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  GEOID NAME                         variable   estimate   moe\n  <chr> <chr>                        <chr>         <dbl> <dbl>\n1 36001 Albany County, New York      B25064_001     1252    22\n2 36003 Allegany County, New York    B25064_001      754    33\n3 36005 Bronx County, New York       B25064_001     1436    11\n4 36007 Broome County, New York      B25064_001      914    26\n5 36009 Cattaraugus County, New York B25064_001      759    30\n6 36011 Cayuga County, New York      B25064_001      895    39\n```\n\n\n:::\n:::\n\n\nI get 62 rows, which match the number of counties in New York State.\n\n---\n\n## How big is the margin of error?\n\nA margin of error of 3,000 means something very different for an estimate of 20,000\nthan for an estimate of 200,000. To compare across places, we need it as a\npercentage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(moe_pct = moe / estimate * 100)\n```\n:::\n\n\nNow sort to see which counties are measured least reliably.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data %>%\n  arrange(desc(moe_pct)) %>%\n  select(NAME, estimate, moe, moe_pct) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                        estimate   moe moe_pct\n   <chr>                          <dbl> <dbl>   <dbl>\n 1 Hamilton County, New York        860    95   11.0 \n 2 Schuyler County, New York        858    75    8.74\n 3 Greene County, New York          993    79    7.96\n 4 Lewis County, New York           821    59    7.19\n 5 Orleans County, New York         877    60    6.84\n 6 Yates County, New York           802    46    5.74\n 7 Wyoming County, New York         782    44    5.63\n 8 Cortland County, New York        911    50    5.49\n 9 Chenango County, New York        819    44    5.37\n10 Livingston County, New York      912    48    5.26\n```\n\n\n:::\n:::\n\n\nHamilton County has the largest relative margin of error for median gross rent in New York State. Its estimated median gross rent is $860, with a margin of error of $95, or about 11.0% of the estimate.\n\n---\n\n## Sorting counties into reliability categories\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(reliability = case_when(\n    moe_pct < 5  ~ \"High confidence\",\n    moe_pct < 10 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability         n\n  <chr>           <int>\n1 High confidence    51\n2 Low confidence      1\n3 Moderate           10\n```\n\n\n:::\n:::\n\n\nAmong New York’s 62 counties, 51 are classified as high confidence, 10 as moderate, and 1 as low confidence.\n\n---\n\n## Is the margin of error bigger in small places?\n\nTo answer this we need population and our variable side by side, in the same row.\nThat means a **wide** pull.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- get_acs(\n  geography = \"county\",\n  variables = c(myvar = my_variable,\n                pop   = \"B01003_001\"),\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\nhead(county_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  GEOID NAME                         myvarE myvarM    popE  popM\n  <chr> <chr>                         <dbl>  <dbl>   <dbl> <dbl>\n1 36001 Albany County, New York        1252     22  315374    NA\n2 36003 Allegany County, New York       754     33   47027    NA\n3 36005 Bronx County, New York         1436     11 1419250    NA\n4 36007 Broome County, New York         914     26  197738    NA\n5 36009 Cattaraugus County, New York    759     30   76479    NA\n6 36011 Cayuga County, New York         895     39   75464    NA\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- county_wide %>%\n  mutate(moe_pct = myvarM / myvarE * 100) %>%\n  mutate(reliability = case_when(\n    moe_pct < 5  ~ \"High confidence\",\n    moe_pct < 10 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n```\n:::\n\n\n\nNow compare the average population of counties in each reliability category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide %>%\n  group_by(reliability) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  reliability     n_counties avg_population\n  <chr>                <int>          <dbl>\n1 High confidence         51        381479.\n2 Low confidence           1          5102 \n3 Moderate                10         41178.\n```\n\n\n:::\n:::\n\nI use the 5% and 10% thresholds established in the previous section so that each reliability category has the same meaning throughout the analysis. This ensures that the population comparison uses the same county classifications as the earlier reliability summary.\n\n**High-confidence counties have an average population of about 381,479, while moderate-confidence counties average about 41,178. The only low-confidence county, Hamilton County, has a population of 5,102. This pattern suggests that median gross rent estimates are less reliable in counties with smaller populations, although the low-confidence category contains only one county.**\n\n---\n\n## What this means for policy\n\n**Which communities in your state do we know the least about?**\n\nThis analysis shows that New York’s smallest counties tend to have the least reliable median gross rent estimates.   Hamilton County is the clearest example: its estimated median gross rent is $860 with a margin of error of $95, or about 11.0 percent. It is the only low-confidence county under the 10 percent cutoff and has only 5,102 residents. Schuyler County has the next-highest relative margin of error at 8.7 percent, followed by Greene County at 8.0 percent.\n\n\n\n**Why?**\n\nThese differences reflect how the American Community Survey works. The ACS draws estimates from a sample rather than counting every household. Smaller counties generally contain fewer sampled households, so a small number of responses can have a larger effect on their estimates. In these results, high-confidence counties average about 381,479 residents, compared with 41,178 in moderate-confidence counties and 5,102 in the low-confidence county. This pattern indicates that estimates become less precise as county population decreases.\n\n**What could go wrong?**\n\nIf a state agency allocated housing assistance using median gross rent while treating every estimate as equally certain, small rural counties could be harmed. An underestimated rent could make a county appear less burdened and cause it to receive too little funding, while an overestimate could divert funds from places with greater need. Renters in Hamilton, Schuyler, and Greene Counties may therefore be especially vulnerable. Agencies should consider both the estimates and their margins of error, and they should avoid making major funding decisions based on small differences that may reflect sampling uncertainty.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}